// client-vue/src/components/App.vue
<template>
  <div class="app">
    <h1>Welcome to Vue!</h1>
    <div class="app__links">
      <router-link to="/">Home</router-link>
      <router-link to="/otherpage">Other Page</router-link>
    </div>
    <router-view />
  </div>
</template>

<style lang="scss">
@import "~#/main.scss";
.app {
  display: flex;
  flex-direction: column;
  align-items: center;
}
</style>

// client-react/src/App.js
import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom'
import './App.css';
import OtherPage from './OtherPage'
import Fib from './Fib'

class App extends Component {
  render() {
    return (
      <Router>
        <div className="App">
          <header className="">
            <h1 className="App-title">Welcome to React!</h1>
            <Link to="/">Home</Link>
            <Link to="/otherpage">Other Page</Link>
          </header>
          <div>
            <Route exact path="/" component={Fib} />
            <Route path="/otherpage" component={OtherPage} />
          </div>
        </div>
      </Router>
    )
  }
}

export default App;
